owner: phpbbmodders # GitHub username
repo: status # GitHub repository name
sites: # List of endpoints to track
  - name: phpBBModders.com
    url: https://www.phpbbmodders.com
  - name: phpBBModders.net
    url: https://www.phpbbmodders.net
assignees: # Users to assign downtime issues (optional)
  - bonelifer
status-website: # Status website (optional)
  cname: status.phpbbmodders.net # Custom domain CNAME
  name: phpBB Modders Status Page # Status website title

  navbar:
    - title: Status
      href: /
    - title: phpBBModders.com
      href: https://phpbbmodders.com
    - title: phpBBModders.net
      href: https://phpbbmodders.net
user-agent: phpBBModders UPTIME
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
